### ISSUE TITLE
Determining if a symbol is "truly unique" doesn't really make sense.

### ISSUE THREAD

**Issue by theScottyJam** [tc39/proposal-symbol-predicates#7]
The stated use-case for the `Symbol.isWellKnown()` function is to allow a library author to detect if a symbol is "truly unique". This use-case doesn't make much sense to me though. If I were to take a guess, the thought process behind the introduction of `isWellKnown()` is to allow API authors to create a function that accepts a symbol as a parameter, and modifies an object we'll call `foo` to use that symbol as a key, and they're wanting to avoid giving `foo` special behaviors due to accidentally using a symbol that related to a built-in protocol. However, I don't think we should privilege built-in protocols over user-defined ones, and it's very possible that some third-party library which I'll call `barLib` also provides protocol implementations and symbols to go with them, and you wouldn't want to use barLib's symbols as keys on your `foo` object either (unless, you can guarantee that the `foo` object and barLib will never meet, then it doesn't really matter much).

**Comment by ljharb** [comment]
Built-in protocols are already privileged over user-defined ones, because they're cross-realm values. Thus, that needs a way to detect it.
