### ISSUE TITLE
Why not prototype methods?

### ISSUE THREAD

**Issue by rauschma** [tc39/proposal-symbol-predicates#8]
Explain that in an FAQ? I’m assuming that the methods are considered to be at the meta level and you want them to be separate from the base level API(?)

**Comment by rauschma** [comment]
There’s really not much difference and either static or prototype should be fine (AFAICT). Maybe:

* Less to type.
* Easier to discover. (I always check prototype methods first.)

For my code, I prefer prototype methods unless there are downsides (such as accidental overrides).

**Comment by ljharb** [comment]
Personally I have the opposite preference - i only ever use prototype methods when they rely on `this` or are valuable in chaining, and predicates in particular I prefer statics because a common use case is `array.filter(predicate)` and friends.

**Comment by rauschma** [comment]
> a common use case is `array.filter(predicate)` and friends.

Due to the “accidentally filling in optional parameters” pitfall, I rarely do that. But others may appreciate being able to do that.

**Comment by michaelficarra** [comment]
Another motivation may be that we currently use the Symbol namespace as a dumping ground for references to well-known symbols (for better or worse, but actually it's for worse) and these methods will share that namespace.

**Comment by ljharb** [comment]
Given that `Symbol.for` and `Symbol.keyFor` exist, current dynamic code already has to filter for `typeof` `"symbol"`, so I'm not sure that impacts the decision much.

**Comment by michaelficarra** [comment]
I wasn't thinking about reflection code enumerating the namespace, just that it's not ideal to mix the concepts and share that namespace. Of course, we've already made that mistake at least twice, but it doesn't mean we must continue.

**Comment by ljharb** [comment]
I would think that if we;re going to make an improvement, it’d be to namespace well-known symbols under a single property on Symbol, not to prompt design decisions on things that aren’t well-known symbols.
